version: "3.9"

services:
  build: ./
  tickRecorder:
    entrypoint: tickRecorder --config /usr/etc/config/tickRecorder
    volumes:
      - ./tmp:/data/tickRecorder/storage/
  replayTradingo:
    entrypoint: replayTradingo --config /usr/etc/config/
    volumes:
      - ./tmp:/data/tickRecorder/storage/
      - ./tmp:/data/tickRecorder/storage/

volumes:
  data: {}