name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name:  Install dependencies
      run: |
        sudo apt-get update && sudo apt-get -y install cmake libcpprest-dev libgtest-dev libboost-program-options-dev \
          && git clone https://github.com/google/benchmark.git /tmp/src/benchmark \
          && mkdir -p /tmp/src/benchmark/build \
          && /bin/sh -c 'cd /tmp/src/benchmark/build && \
            cmake -DBENCHMARK_DOWNLOAD_DEPENDENCIES=on \
            -DCMAKE_BUILD_TYPE=Release /tmp/src/benchmark \
            && sudo make install -j3 '
    - name: Clone thirdparty modules
      run: git submodule init && git submodule update

    - name: Build Api Connectors
      run: BUILD_TYPE=Debug ${{github.workspace}}/autogen-swagger.sh

    - name: Build Tradingo
      run: BUILD_TYPE=Debug ${{github.workspace}}/autogen.sh && cd ${{github.workspace}}/build.debug && make install -j4

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ctest -C ${{env.BUILD_TYPE}} --verbose
