name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name:  Install dependencies
      run: |
        sudo apt-get update && sudo apt-get -y install \
            cmake \
            libcpprest-dev \
            libgtest-dev \
            libcurl4-openssl-dev \
            libboost-program-options-dev \

    - name: Clone thirdparty modules
      run: git submodule init && git submodule update

    - name: Build AWS SDK
      run: BUILD_TYPE=Release ${{github.workspace}}/autogen-deps.sh 

    - name: Build Api Connectors
      run: BUILD_TYPE=Debug ${{github.workspace}}/autogen-swagger.sh

    - name: Build Tradingo
      run: BUILD_TYPE=Debug ${{github.workspace}}/autogen.sh

    - name: Test
      working-directory: ${{github.workspace}}/build.debug/
      run: ctest -C ${{env.BUILD_TYPE}} --verbose
